-- MySQL Script generated by MySQL Workbench
-- qui 07 jan 2021 19:03:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zoomilho
-- -----------------------------------------------------
-- 
-- 

-- -----------------------------------------------------
-- Schema zoomilho
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zoomilho` ;
USE `zoomilho` ;

-- -----------------------------------------------------
-- Table `zoomilho`.`gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoomilho`.`gerente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_gerente` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_idade_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoomilho`.`nome_cuidador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoomilho`.`nome_cuidador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_cuidador` VARCHAR(80) NULL,
  `gerente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_nome_cuidador_gerente1_idx` (`gerente_id` ASC) VISIBLE,
  CONSTRAINT `fk_nome_cuidador_gerente1`
    FOREIGN KEY (`gerente_id`)
    REFERENCES `zoomilho`.`gerente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoomilho`.`sexo_do_animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoomilho`.`sexo_do_animal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sexo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_sexo_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoomilho`.`localizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoomilho`.`localizacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `localizacao` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_localizacao_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoomilho`.`especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoomilho`.`especie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_especie` VARCHAR(80) NULL,
  `nome_cuidador_id` INT NOT NULL,
  `sexo_do_animal_id` INT NOT NULL,
  `localizacao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_especie_nome_cuidador_idx` (`nome_cuidador_id` ASC) VISIBLE,
  INDEX `fk_especie_sexo_do_animal1_idx` (`sexo_do_animal_id` ASC) VISIBLE,
  INDEX `fk_especie_localizacao1_idx` (`localizacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_especie_nome_cuidador`
    FOREIGN KEY (`nome_cuidador_id`)
    REFERENCES `zoomilho`.`nome_cuidador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_especie_sexo_do_animal1`
    FOREIGN KEY (`sexo_do_animal_id`)
    REFERENCES `zoomilho`.`sexo_do_animal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_especie_localizacao1`
    FOREIGN KEY (`localizacao_id`)
    REFERENCES `zoomilho`.`localizacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoomilho`.`idade_animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoomilho`.`idade_animal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idade` INT NULL,
  `especie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_idade_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_idade_animal_especie1_idx` (`especie_id` ASC) VISIBLE,
  CONSTRAINT `fk_idade_animal_especie1`
    FOREIGN KEY (`especie_id`)
    REFERENCES `zoomilho`.`especie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
